INSERT INTO games (name, console, progress, description, rating, is_favorite) VALUES
('Overwatch', 'Xbox', 'Currently Playing', 'Overwatch is a 2016 team-based multiplayer first-person shooter game developed and published by Blizzard Entertainment. Described as a "hero shooter", Overwatch assigns players into two teams of six, with each player selecting from a large roster of characters, known as "heroes", with unique abilities!', 4, true),
('Hollow Knight', 'Xbox', 'Completed', 'Hollow Knight is a classically styled 2D action adventure across a vast interconnected world. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and solve ancient mysteries at the kingdoms heart.', 5, true),
('Super Mario Odyssey', 'Switch', 'Backlogged', 'Super Mario Odyssey is a platform game in which players control Mario as he travels across many different worlds, known as "Kingdoms" within the game, on the hat-shaped ship Odyssey, to rescue Princess Peach from Bowser, who plans to forcibly marry her.', 5, true),
('Call of Duty: Warzone', 'Xbox', 'Abandoned', 'Call of Duty: Warzone is a free-to-play battle royale. Warzone allows online multiplayer combat among 150 players, although some limited-time game modes support 200 players.', 1, false),
('Fall Guys', 'Playstation', 'Currently Playing', 'Fall Guys (formerly known as Fall Guys: Ultimate Knockout) is a platform battle royale game developed by Mediatonic. The game involves up to 60 players who control jellybean-like creatures and compete against each other in a series of randomly selected mini-games, such as obstacle courses or tag.', 5, false),
('Super Mario Galaxy', 'Wii', 'Completed', 'Super Mario Galaxy is set in outer space, where Mario travels through different galaxies to collect Power Stars, earned by completing missions, defeating a boss, or reaching a particular area. Each galaxy contains planetoids and orbiting structures for the player to explore.', 5, true),
('Spider-man', 'Playstation', 'In Progress', 'Marvels Spider-Man is an open-world third-person action-adventure game, in which the player controls Peter Parker, under his superhero identity Spider-Man, through Manhattan, New York City to fight crime.', 3, false),
('Super Mario Bros. 2', 'Gameboy Advanced', 'Completed', 'Super Mario Bros. 2 is a 2D side-scrolling platform game. The objective is to navigate the players character through the dream world Subcon and defeat the main antagonist Wart. Before each stage, the player chooses one of four protagonists: Mario, Luigi, Toad, and Princess Toadstool.', 5, false),
('Fortnite', 'Xbox', 'Currently Playing', 'Fortnite is a survival game where 100 players fight against each other in player versus player combat to be the last one standing. It is a fast-paced, action-packed game, not unlike The Hunger Games, where strategic thinking is a must in order to survive.', 4, true),
('Dead Cells', 'Xbox', 'Currently Playing', 'Dead Cells is a rogue-lite, Castlevania-inspired action-platformer, allowing you to explore a sprawling, ever-changing castle… assuming you''re able to fight your way past its keepers. To beat the game, you''ll have to master 2D "souls-lite combat" with the ever-present threat of permadeath looming. No checkpoints.', 3, false),
('Celeste', 'Xbox', 'Completed', 'Celeste is a platform game in which players control a young woman named Madeline as she makes her way up Mount Celeste while avoiding various deadly obstacles. Along with jumping and climbing up walls for a limited amount of time, Madeline has the ability to perform a mid-air dash in eight directions.', 5, true),
('It Takes Two', 'Xbox', 'Completed', 'Play as the clashing couple Cody and May, two humans turned into dolls by a magic spell. Trapped in a fantastical world, they''re reluctantly challenged with saving their fractured relationship by the suave love guru Dr. Hakim.', 5, false);